# Try out GraphQL queries here
query GetCustomer($id: Float!) {
  getCustomer(findCustomer: { id: $id }) {
    id
    username
    tasks {
      id
      product
    }
  }
}

query MyQuery {
  customers {
    username
  }
}
