# Try out GraphQL queries here
query GetCustomerById($id: Float!) {
  getCustomer(customerId: $id) {
    username
    tasks {
      name
    }
  }
}

query GetCustomers {
  customers {
    username
    tasks {
      name
    }
  }
}
