# Try out GraphQL queries here
query GetCustomerById($id: String!) {
  getCustomer(customerId: $id) {
    email
    tasks {
      name
    }
  }
}

query GetCustomers {
  customers {
    email
    tasks {
      name
    }
  }
}
