query GetTaskById($id: Float!) {
  getTask(taskId: $id) {
    name
    customer {
      username
    }
  }
}

query GetTasks {
  tasks {
    name
    customer {
      username
    }
  }
}

mutation InsertTask($name: String!, $customer_id: Int!) {
  insert_tasks_one(object: { name: $name, customer_id: $customer_id }) {
    id
    name
    customer {
      username
    }
  }
}

mutation UpdateTask($id: Int!, $name: String!) {
  update_tasks_by_pk(
    pk_columns: { id: $id }
    _set: { name: $name, updated_at: now }
  ) {
    id
    name
  }
}
