query GetTaskById($id: Float!) {
  getTask(taskId: $id) {
    name
    customer {
      username
    }
  }
}

query GetTasks {
  tasks {
    name
    customer {
      username
    }
  }
}

mutation InsertTask($newTask: tasks_insert_input!) {
  insert_tasks_one(object: $newTask) {
    id
    name
    customer {
      username
    }
  }
}
