query GetTaskById($id: Float!) {
  getTask(taskId: $id) {
    name
    customer {
      email
    }
  }
}

query GetTasks {
  tasks {
    name
    customer {
      email
    }
  }
}

subscription GetTasksSubscription {
  tasks {
    id
    name
  }
}

mutation InsertTask($name: String!, $customer_id: String!) {
  insert_tasks_one(object: { name: $name, customer_id: $customer_id }) {
    id
    name
    customer {
      email
    }
  }
}

mutation RemoveTask($task_id: Int!) {
  delete_tasks(where: { id: { _eq: $task_id } }) {
    affected_rows
  }
}

mutation UpdateTask($id: Int!, $name: String!) {
  update_tasks_by_pk(
    pk_columns: { id: $id }
    _set: { name: $name, updated_at: now }
  ) {
    id
    name
  }
}
